-   id: add-issue-number
    name: Add issue number
    description: Looks for an issue number in the current branch name and adds it to the conventional commit
    entry: add-issue-number-to-conventional-commit
    language: python
    stages: [prepare-commit-msg]
