default_install_hook_types:
  - pre-commit
  - prepare-commit-msg
repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-simplify
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.0.4
    hooks:
      - id: validate_manifest
  - repo: https://gitlab.com/codementors/pre-commit/add-issue-number-to-conventional-commit
    rev: v0.0.1
    hooks:
      - id: add-issue-number
