name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.14

      - name: Install dependencies
        run: pip install '.[dev]'

      - name: Run tests
        run: tox

      - name: Copy coverage report
        # if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: cp .coverage/coverage.json coverage.json

      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        # if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@8a0b6ee05f6dd0f294089cbe7a848452a2b43eef # main@2026-05-05
        env:
          PRE_COMMIT_ALLOW_NO_CONFIG: 1
